const fs = require("fs");
const path = require("path");
const { pipeline } = require("stream/promises");
const { Transform } = require("stream");
const config = require("../../config");
const { createUploadToken } = require("../tokens");
const { HttpError } = require("../errors");

// Files in a local folder. For tests and quick local runs: production should
// use object storage, since a server's disk isn't shared between instances
// and many hosts wipe it on every deploy.
//
// To keep one upload flow for both drivers, "signed upload URLs" here point
// at the API itself (PUT /api/uploads/:token), which streams to disk.

const root = path.resolve(config.uploadDir);
fs.mkdirSync(root, { recursive: true });

// Keys are generated by the server (shares/<shareId>/<fileId>), but never
// trust a path: anything that resolves outside the folder is refused.
const pathFor = (key) => {
    const full = path.resolve(root, key);
    if (!full.startsWith(root + path.sep)) throw new Error(`Invalid storage key: ${key}`);
    return full;
};

const ignoreMissing = (err) => {
    if (err.code !== "ENOENT") throw err;
};

const createDiskStorage = () => ({
    driver: "disk",
    // Files are served by this server, so no extra origin for the CSP.
    publicOrigin: null,

    async init() {
        await fs.promises.mkdir(root, { recursive: true });
    },

    async health() {
        return "disk";
    },

    async createUploadTarget({ key, size, contentType }) {
        return {
            method: "PUT",
            url: `/api/uploads/${createUploadToken({ key, size })}`,
            headers: { "Content-Type": contentType },
        };
    },

    // Streams a request body to `key`, refusing anything but exactly `size`
    // bytes. Written to a temp file first, so a failed upload leaves nothing.
    async receiveUpload(req, { key, size }) {
        const target = pathFor(key);
        const temp = `${target}.${process.pid}.${Date.now()}.part`;
        await fs.promises.mkdir(path.dirname(target), { recursive: true });

        let received = 0;
        const counter = new Transform({
            transform(chunk, encoding, callback) {
                received += chunk.length;
                if (received > size) callback(new HttpError(413, "The upload is larger than the file announced"));
                else callback(null, chunk);
            },
        });

        try {
            await pipeline(req, counter, fs.createWriteStream(temp));
            if (received !== size) {
                throw new HttpError(400, `Expected ${size} bytes but received ${received}`);
            }
            await fs.promises.rename(temp, target);
        } catch (err) {
            await fs.promises.rm(temp, { force: true });
            throw err;
        }
    },

    async stat(key) {
        try {
            const stats = await fs.promises.stat(pathFor(key));
            return { size: stats.size };
        } catch (err) {
            ignoreMissing(err);
            return null;
        }
    },

    async readStart(key, bytes) {
        const handle = await fs.promises.open(pathFor(key), "r");
        try {
            const buffer = Buffer.alloc(bytes);
            const { bytesRead } = await handle.read(buffer, 0, bytes, 0);
            return buffer.subarray(0, bytesRead);
        } finally {
            await handle.close();
        }
    },

    async sendDownload(res, { key, contentType, contentDisposition }) {
        await new Promise((resolve, reject) => {
            res.sendFile(
                pathFor(key),
                {
                    headers: {
                        "Content-Type": contentType,
                        "Content-Disposition": contentDisposition,
                        "Cache-Control": "private, no-store",
                    },
                },
                (err) => (err ? reject(err) : resolve())
            );
        });
    },

    async delete(keys) {
        await Promise.all(keys.map((key) => fs.promises.unlink(pathFor(key)).catch(ignoreMissing)));
        // Tidy up now-empty share folders (fails harmlessly if not empty).
        const dirs = new Set(keys.map((key) => path.dirname(pathFor(key))).filter((dir) => dir !== root));
        await Promise.all([...dirs].map((dir) => fs.promises.rmdir(dir).catch(() => {})));
    },

    // Every stored file, for the orphan sweep.
    async *list() {
        const entries = await fs.promises.readdir(root, { recursive: true, withFileTypes: true });
        for (const entry of entries) {
            if (!entry.isFile() || entry.name.endsWith(".part")) continue;
            const full = path.join(entry.parentPath ?? entry.path, entry.name);
            const stats = await fs.promises.stat(full).catch(() => null);
            if (stats) yield { key: path.relative(root, full).split(path.sep).join("/"), modifiedAt: stats.mtime };
        }
    },
});

module.exports = { createDiskStorage };
